### ISSUE TITLE
Unused variable newMainMachine in LRPCompare

### ISSUE THREAD

**Issue by jfabry** [jfabry/LiveRobotProgramming#104]
It appears that the variable `newMainMachine` is only set but never read. In any case it is never used in tests. Please double check and if it is not required remove it. If it is required, make sure that there is a test that covers it.

**Comment by mcamp** [comment]
Maybe it was intended to be used, but I also don't see the point now. It was removed

Name: LiveRobotics-Interpreter-mcamp.119
Author: mcamp
Time: 4 January 2016, 5:05:18.135142 pm
UUID: 232c9ccd-fe8c-4e4c-987a-1723c99ff8c2
Ancestors: LiveRobotics-Interpreter-johanfabry.118

Removed newMainMachine, as stated in issue #104.
