### ISSUE TITLE
OpenUI abstract method requires that its implementation returns a ComposableModel instance

### ISSUE THREAD

**Issue by carolahp** [jfabry/LiveRobotProgramming#121]
If the OpenUI implementation doesn't return a ComposableModel, and instead returns self (by default), the method closeUI sends the message "delete" to an object that doesn't understand it.

**Comment by jfabry** [comment]
Feel free to add & commit the fix we talked about last meeting.

**Comment by jfabry** [comment]
Protocol of openUI / closeUI was not immediately clear, but good enough in the end. We can leave it as is.
