### ISSUE TITLE
Robot reset method would be apreciated

### ISSUE THREAD

**Issue by carolahp** [jfabry/LiveRobotProgramming#122]
After opening LRP it is not possible to re initialize the robot instance. It would be very useful to have a reset method.

**Comment by jfabry** [comment]
It's not clear to me what the reset method should do, can you explain your problem in a bit more detail?

**Comment by mcamp** [comment]
Caro was working with the drone and from time to time the drone disconnected from Pharo (and the API). In LRP, this means the robot variable is no longer useful and, to reconnect to the drone, LRP should be restarted. It would be nice to not make a reconnection.
However, this can be a little difficult depending on the different bridges, more specifically, the ROS bridge. This feature needs a bit of thinking

**Comment by jfabry** [comment]
OK so it seems to me that this is something that is specific to the bridge itself, like the topics in the ROSbridge and the IP address selection of the EV3 Bridge.
So, @carolahp I think this is something that you should implement in the drone bridge first, and then we can see if it can be generalized or not.
