### ISSUE TITLE
The UI does not keep freeze movement state

### ISSUE THREAD

**Issue by mcamp** [jfabry/LiveRobotProgramming#123]
When I click freeze movement in the UI, this option is resseted everytime I do an action (ie, change the machine to visualize or editting the code).
It should stay freeze/unfreeze with every action, it should not change to unfreeze everytime

**Comment by jfabry** [comment]
With respect to changing to a different machine, this cannot be fixed until issue #125 is fixed, otherwise the nodes of a machine would never be layout.
As for no layout when editing actions this is not possible either since it would mean that adding new states would not be visible.

**Comment by jfabry** [comment]
Fixed thanks to the fix of issue #125
