### ISSUE TITLE
There is no visualization for exit transition

### ISSUE THREAD

**Issue by mcamp** [jfabry/LiveRobotProgramming#129]
For the new "exit" statement, in the visualization there is no indication of this statement. To fix this we need to: 
 - Draw a tx between the state with the nested machine to the next state.
 - Draw a special tx in the nested state machine to show from which state this "exit" statement come from, and we have to be clear that this tx is an exit tx

**Comment by jfabry** [comment]
Any suggestions on how to draw the 'special tx' ?

**Comment by jfabry** [comment]
Fixed in `LiveRobotics-Parser-johanfabry.72` @mcamp In the inner machine there is no 'special tx'. I think the current fix is enough: a transition in the outer machine that has the name `Exit`. Plus clicking on it goes to the exit statement in the source code.
