### ISSUE TITLE
exit statement does not have a syntax highlighting 

### ISSUE THREAD

**Issue by mcamp** [jfabry/LiveRobotProgramming#130]
The exit statement needs to be highlighted like every other statement in LRP

**Comment by jfabry** [comment]
Underlying problem is that there is no exit statement being generated for the AST, there is direct translation to a bunch of AST nodes. So no statement to set highlighting info. I will need to add a sugar-highlight node to support this for different kinds of sugar.

**Comment by jfabry** [comment]
Fixed in `LiveRobotics-Parser-johanfabry.71`, `LiveRobotics-Interpreter-johanfabry.156` and `LiveRobotics-UI-johanfabry.161`. Only the keyword is made italic, but I guess that's enough for now.
