### ISSUE TITLE
freeze movement when copy two machines in a new lrp program

### ISSUE THREAD

**Issue by mcamp** [jfabry/LiveRobotProgramming#135]
if you copy the program:
(machine foo
	(state a
		(machine bar
			(state c)
		)
	)
	(state b)
)

There are 2 problems:
1. There is no default visualization of any machine 
2. When you click on a machine to visualize, the freeze option is activated, collapsing all states to a single point in the visualization

**Comment by jfabry** [comment]
First issue also fixed, done in `LiveRobotics-UI-johanfabry.171`
