### ISSUE TITLE
Current LiveRobotProgramming.image is nor working in Pharo5

### ISSUE THREAD

**Issue by andresmore** [jfabry/LiveRobotProgramming#161]
![image](https://user-images.githubusercontent.com/2692503/46897964-69efea80-ce4b-11e8-847e-3e254861a281.png)
Current image is not loading in Pharo5

Displays error MessageNotUnderstood:receiver of "owner:" is nil

**Comment by lesterlecong** [comment]
The same issue here. It is looking for RoassalModel class. I don't know where to get it.

**Comment by jfabry** [comment]
I'm sorry to say that I am no longer actively supporting LRP. A workaround for your issue may be the following:

- Download Pharo 6.1
- From the Project Catalog (World->Tools->Catalog browser) Load the Roassal2 project (search for it, then press the green checkmark)
- Load LRP from source by opening a Playground, pasting the text below and pressing the green triangle-arrow-thingy on the top right

``` Smalltalk
Gofer it
  smalltalkhubUser: 'jfabry' project: 'LiveRobotProgramming';
  configuration;
  loadDevelopment
```

**Comment by mcamp** [comment]
LRP is working fine in Pharo 7.
I recommend using LRP in that version of Pharo
