### ISSUE TITLE
Clean up syntax highlight hierarchy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jfabry/LiveRobotProgramming#45]
```
- The LRPStyler hierarchy should be collapsed.
- The parser holds a reference to the styler class which makes the parser 
package dependent on the ui package. This should be removed 


```

Original issue reported on code.google.com by `jfa...@gmail.com` on 21 Jan 2015 at 9:33

**Comment by jfabry** [comment]
The parser no longer has a reference to the styler. Done as part of the integration of the PP compiler

**Comment by jfabry** [comment]
Fixed in LiveRobotics-UI-johanfabry.112
