### ISSUE TITLE
LRPUserInterface>>varChange:inMachine: always refreshes the variable list 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jfabry/LiveRobotProgramming#54]
```
It should do this only if a variable changed that we are actually displaying. 
And ideally only change that variable in the list.
```

Original issue reported on code.google.com by `jfa...@gmail.com` on 28 Mar 2015 at 4:49

**Comment by jfabry** [comment]
We don't get the info of what machine's variable has been changed so we cannot be very clever about it.  Here is some code for testing:

;;; New program created by johanfabry on 25 September 2015
(machine m
	(var top := [0])
	(state one
		(machine nest
			(var in := [0])
			(state none (onentry [in := in + 1])))
		(onentry (spawn nest none))
		)
	(state two
		(machine nest2
			(var in2 := [0])
			(state none)
			(state ntwo (onentry [in2 := in2 + 1]))
			(ontime 500 none -> ntwo)
			(ontime 500 ntwo -> none)
			)
			(onentry  (spawn nest2 ntwo)))
)
(spawn m two)

**Comment by jfabry** [comment]
Partial fix using the name of the variable to see if we need to refresh is in LiveRobotics-UI-johanfabry.99

**Comment by jfabry** [comment]
What we have now is good enough. A bit more clever passing of data + some more comments and clarifications in `LiveRobotics-Interpreter-johanfabry.143` and `LiveRobotics-UI-johanfabry.152`
