### ISSUE TITLE
Check if we still need change checks with weakEqualNode: and bodyEqualNode:

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jfabry/LiveRobotProgramming#68]
```
These are no longer required for transitions, do we need them for something 
else? If not can this logic be cleaned up?
```

Original issue reported on code.google.com by `jfa...@gmail.com` on 22 Jun 2015 at 8:00

**Comment by jfabry** [comment]
Fixed in LiveRobotics-Interpreter-johanfabry.111 Now bodyEqualNode is gone and LRPCompareNodes>>modified is deprecated (it was dead code already, except for the tests)
