### ISSUE TITLE
Load and save should also be feasible from a context menu and keyboard shortcut

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jfabry/LiveRobotProgramming#69]
```
Load and save should also be possible with context menu so we can have keyboard 
shortcuts. Especially the save operation should be easy to perform with a cmd-s 
shortcut.
```

Original issue reported on code.google.com by `jfa...@gmail.com` on 6 Aug 2015 at 12:35

**Comment by jfabry** [comment]
A first go is in LiveRobotics-UI-johanfabry.102
* cmd-d does save, because I cannot remove keybinding for cmd-s using `removeKeyCombination: $s command;`
* alternate route is to subclass `RubTextEditor` and there reimplement `buildShortcutsOn: aBuilder`

**Comment by jfabry** [comment]
I was removing the key combination on the wrong morph. cmd-s works now, as well as cmd-l for load.

Fixed in LiveRobotics-UI-johanfabry.103
