### ISSUE TITLE
Var state is not copied on machine change

### ISSUE THREAD

**Issue by jfabry** [jfabry/LiveRobotProgramming#78]
Code:

(machine m
 (var x := [0])
 (state foo (onentry [x:=42]))
 (event fake [1+2])
)
(spawn m foo)

The value of x is 42, you can see it in the UI. But when you edit the transition the value is reset to 0.
Don't forget the test cases please :-)

**Comment by mcamp** [comment]
which transition do you mean?

**Comment by jfabry** [comment]
Closed because unclear bug report and probably fixed with new variable initialization logic.
