### ISSUE TITLE
On PhaROS Bridge, when creating a publisher or a subscription, the Image freeze

### ISSUE THREAD

**Issue by mcamp** [jfabry/LiveRobotProgramming#82]
When creating a subscription or a publisher, when writing the topic, first appears a warning, then on proceed or abandon, the image freeze

**Comment by mcamp** [comment]
This could be mostly for connections problems between the workstation and the robot, for now we added a time limit to retrieve this information

**Comment by jfabry** [comment]
This is the AIO plugin warning? We should have the bridge replace the method definition of that method to not raise a warning (just have the warning in comments).

**Comment by mcamp** [comment]
Fied in LiveRobotics-UI-PhaROS-mcamp.11
