### ISSUE TITLE
The logic for opening the interpreter should be cleaned up

### ISSUE THREAD

**Issue by jfabry** [jfabry/LiveRobotProgramming#83]
I imagine that ideally there should be 2 ways:
* Start the interpreter headless, with a String that is the program
* Start the interpreter with an UI, passing it the Spec instance of the UI

At least the second one is needed to be able to start the interpreter without the state machine visualization.

**Comment by mcamp** [comment]
Fixed on: 
LiveRobotics-Interpreter-mcamp.110 
LiveRobotics-UI-mcamp.106
