### ISSUE TITLE
When opening LRP cmd+s does not work in nautilus anymore

### ISSUE THREAD

**Issue by mcamp** [jfabry/LiveRobotProgramming#90]

**Comment by jfabry** [comment]
This is a bug in Pharo 5. I will add a bugreport in the pharo fogbugz and link it here. In the mean time I will remove the command-s shortcut overriding in `LRPProgramEditor>>lrpTextArea`

**Comment by jfabry** [comment]
Shortcut overriding commented out in LiveRobotics-UI-johanfabry.115

**Comment by jfabry** [comment]
Bug reported to Pharo community https://pharo.fogbugz.com/f/cases/17304/Morph-removeKeyCombination-removes-shortcut-key-globally-instead-of-locally

**Comment by jfabry** [comment]
Fix committed in LiveRobotics-UI-johanfabry.125. There was no need to remove the existing cmd-s shortcut, simply overriding it works.
