### ISSUE TITLE
Transition here by menu does not spawn nested machines if any

### ISSUE THREAD

**Issue by jfabry** [jfabry/LiveRobotProgramming#93]
Code:
```
(var test := [false])
(machine top
	(state first
		(machine nested
			(state nfirst (onentry [test := true])))
		(onentry (spawn nested nfirst)))
	(state second)
)
(spawn top second)
```
If you do a 'Transition here' to the ```first``` state it should spawn the ```nested``` machine and hence go to ```nfirst``` and set ```test``` to false. This does not happen.

* [ ] we need a test for this
* [ ] the bug should be fixed

**Comment by mcamp** [comment]
Fixed in commit: 
LiveRobotics-Interpreter-mcamp.121

Tests in commit:
LiveRobotics-Tests-mcamp.54
